export const AUDIO_LIMIT=50*1024*1024;
export function audioType(file){const raw=(file.type||'').split(';')[0].toLowerCase();const aliases={'audio/x-m4a':'audio/mp4','audio/m4a':'audio/mp4','audio/x-wav':'audio/wav','audio/mp3':'audio/mpeg'};const type=aliases[raw]||raw;const allowed=['audio/mp4','audio/mpeg','audio/wav','audio/webm','audio/ogg','audio/aac','audio/flac'];if(allowed.includes(type))return type;const ext=(file.name||'').split('.').pop().toLowerCase();if(!raw||raw==='application/octet-stream')return {m4a:'audio/mp4',mp3:'audio/mpeg',wav:'audio/wav',webm:'audio/webm',ogg:'audio/ogg',aac:'audio/aac',flac:'audio/flac'}[ext]||'';return '';}
export function validateAudio(file){if(!file.size)throw Error('錄音是空檔，請重新選擇。');if(file.size>AUDIO_LIMIT)throw Error('單段錄音上限 50 MB，請先分段。');const type=audioType(file);if(!type)throw Error('請選 M4A、MP3、WAV、WebM、OGG、AAC 或 FLAC 音檔，不支援影片。');return type;}
export function createRecorder({save,status,lock}){
 let recorder,stream,timer,ticker,parts=[],active=false,started=0,recovery=null,finish;
 const cleanup=()=>{clearTimeout(timer);clearInterval(ticker);stream?.getTracks().forEach(t=>t.stop());stream=null;};
 const stop=()=>{if(recorder?.state==='recording'){status('正在保存錄音，請留在此頁…');recorder.stop();}return finish;};
 return {get active(){return active;},get recovery(){return recovery;},stop,discard(){recovery=null;lock(false);status('已放棄未保存錄音。');},
 async retry(){if(!recovery)return;lock(true);try{await save(recovery);recovery=null;status('錄音已存本機草稿，請儲存紀錄並試聽。');}finally{lock(false);}},
 async start(){if(active||recovery)throw Error('請先處理目前錄音。');if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw Error('此瀏覽器不支援直接錄音。請用 iPhone 語音備忘錄錄製，再從檔案加入。');active=true;lock(true);status('等待麥克風權限…');try{stream=await navigator.mediaDevices.getUserMedia({audio:true});if(document.hidden)throw Error('請回到 App 前景後再開始錄音。');const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm','audio/ogg;codecs=opus'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)throw Error('未找到支援的錄音格式，請改用語音備忘錄。');recorder=new MediaRecorder(stream,{mimeType:mime});parts=[];let total=0;started=Date.now();finish=new Promise(resolve=>{recorder.ondataavailable=e=>{if(e.data.size){parts.push(e.data);total+=e.data.size;if(total>AUDIO_LIMIT)stop();}};recorder.onerror=()=>{status('錄音被中斷，正在嘗試保存，請試聽確認。');stop();};recorder.onstop=async()=>{cleanup();const type=recorder.mimeType.split(';')[0];const blob=new Blob(parts,{type});parts=[];const ext=type==='audio/mp4'?'m4a':type==='audio/ogg'?'ogg':'webm';recovery=new File([blob],'錄音-'+new Date().toISOString().replace(/[:.]/g,'-')+'.'+ext,{type});try{await save(recovery);recovery=null;status('錄音已存本機草稿。請試聽後儲存紀錄。');}catch(e){status('錄音尚未存好：'+e.message+'。請重試保存或下載暫存音檔，離開會遺失。');}finally{active=false;lock(false);resolve();}};});recorder.start(1000);ticker=setInterval(()=>status('● 錄音中 '+Math.floor((Date.now()-started)/1000)+' 秒；請勿鎖屏／切換 App'),1000);status('● 錄音中，按停止保存；最長 3 分鐘。');timer=setTimeout(stop,180000);}catch(e){cleanup();active=false;lock(false);status(e.name==='NotAllowedError'?'未取得麥克風權限。可改用「從檔案加入錄音」。':e.message);throw e;}}
 };
}
