import {checkVocabulary,termByName} from './ekg.js';
export const SCHEMA=2;
export const LOCATIONS=['展場','賭場','事前資料','其他'];
export const WORKS=['未確認','新作品','系列作品（續作）','改版'];
export const TAGS=['Hold & Spin','Free Game','Cash Collect','Bonus Link','Wild','乘倍','擴展盤面','多盤面','轉盤','收集','解鎖','Buy Bonus','重觸發','累進彩金'];
export function tokens(value){return [...new Set((Array.isArray(value)?value:String(value||'').split(/[,，、\n]/)).map(s=>s.trim()).filter(Boolean))];}
export function safeUrl(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function normalizeTags(value){const aliases={'hold n spin':'Hold & Spin','hold and spin':'Hold & Spin','hold & spin':'Hold & Spin','free game':'Free Game','free games':'Free Game','free spin':'Free Game','free spins':'Free Game'};return [...new Set(tokens(value).map(t=>aliases[t.toLowerCase()]||t))];}
export function validateRecord(r){if(!r.name?.trim())throw Error('請填機台名稱，或保留「名稱待確認」。');if(!LOCATIONS.includes(r.location))throw Error('請選擇地點類型。');if(!WORKS.includes(r.work))throw Error('請選擇作品類型。');for(const u of r.links||[])if(!safeUrl(u))throw Error('相關連結請使用完整的 https:// 或 http:// 網址。');return r;}
export function hasFieldRecord(r){return !!((r.notes||[]).some(n=>n.text?.trim())||(r.mediaIds||[]).some(id=>id.startsWith('photo-'))||(['展場','賭場'].includes(r.location)&&r.userEdited));}
export function filterRecords(records,f={}){const q=(f.q||'').trim().toLowerCase();return records.filter(r=>!!r.archived===!!f.archived&&(!q||[r.name,r.vendor,r.family,r.description,r.artNotes,...(r.tags||[]).flatMap(t=>[t,termByName.get(t)?.term_zh||'']),...(r.legacyTags||[]),...(r.styles||[]),...(r.notes||[]).map(n=>n.text)].join(' ').toLowerCase().includes(q))&&(!f.vendor||r.vendor===f.vendor)&&(!f.location||r.location===f.location)&&(!f.tag||(r.tags||[]).includes(f.tag))&&(!f.work||r.work===f.work)&&(!f.kind||r.kind===f.kind)&&(!f.state||f.state==='seen'&&r.seen||f.state==='unseen'&&!r.seen||f.state==='star'&&r.priority==='必看'||f.state==='edited'&&hasFieldRecord(r)||f.state==='missing'&&!r.mediaIds.length));}
export function csv(records){const cols=['編號','地點','地點補充','廠商','機台名稱','作品','說明','Tag','主題、美術風格','美術說明','圖片編號','舊標籤（非EKG待對照）','相關連結','現場筆記','待確認','已看'];const cell=x=>'"'+String(x??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';return '\ufeff'+[cols,...records.map(r=>[r.id,r.location,r.locationDetail,r.vendor,r.name,r.work,r.description,(r.tags||[]).join('、'),(r.styles||[]).join('、'),r.artNotes,r.mediaIds.join('、'),(r.legacyTags||[]).join('、'),r.links.join('\n'),r.notes.map(n=>`${n.createdAt} ${n.text}`).join('\n'),r.todo,r.seen?'已看':'未看'])].map(row=>row.map(cell).join(',')).join('\r\n');}
export function checkBackup(b){
 if(b?.glossary!==undefined)checkVocabulary(b.glossary);
 if(b?.format!=='g2e-field-notes'||![1,SCHEMA].includes(b.schema))throw Error('不是支援的展場資料備份，請選擇由本 App 匯出的 JSON 檔。');
 if(!Array.isArray(b.records)||!Array.isArray(b.media)||!Array.isArray(b.vendors)||b.records.length>20000||b.media.length>20000)throw Error('備份結構或筆數不正確。');
 const mids=new Set();for(const m of b.media){if(typeof m.id!=='string'||mids.has(m.id)||typeof m.name!=='string'||typeof m.data!=='string'||!/^data:image\/(jpeg|png|webp|gif|heic|heif);base64,[A-Za-z0-9+/]*={0,2}$/.test(m.data))throw Error('圖片備份格式不正確或包含重複編號。');mids.add(m.id);}
 const ids=new Set();for(const r of b.records){if(typeof r.id!=='string'||ids.has(r.id)||!Array.isArray(r.mediaIds)||!Array.isArray(r.links)||!Array.isArray(r.notes)||!Array.isArray(r.tags)||!Array.isArray(r.styles)||typeof r.vendor!=='string'||typeof r.description!=='string'||!Number.isFinite(Date.parse(r.updatedAt)))throw Error('機台備份欄位不完整或編號重複。');for(const k of ['name','location','work','kind','artNotes','todo','locationDetail','family'])if(r[k]!==undefined&&typeof r[k]!=='string')throw Error('機台欄位類型不正確。');for(const k of ['tags','styles','links','mediaIds'])if(r[k].some(x=>typeof x!=='string'))throw Error('標籤、連結或圖片編號格式不正確。');if(r.sources!==undefined&&(!Array.isArray(r.sources)||r.sources.some(x=>!x||typeof x.text!=='string'||typeof x.url!=='string')))throw Error('文章來源格式不正確。');if(r.legacyTags!==undefined&&(!Array.isArray(r.legacyTags)||r.legacyTags.some(x=>typeof x!=='string')))throw Error('舊標籤格式不正確。');validateRecord(r);for(const id of r.mediaIds)if(!mids.has(id))throw Error('備份缺少圖片，未還原任何資料。');for(const n of r.notes)if(!n||typeof n.text!=='string')throw Error('筆記格式不正確。');ids.add(r.id);}
 const casinos=b.casinos??[];if(!Array.isArray(casinos)||casinos.length>20000)throw Error('賭場備份格式不正確。');
 const cids=new Set();for(const c of casinos){validateCasino(c);if(cids.has(c.id))throw Error('賭場編號重複。');cids.add(c.id);for(const mid of c.mediaIds)if(!mids.has(mid))throw Error('賭場備份缺少圖片。');}
 const vids=new Set();for(const v of b.vendors){if(typeof v.id!=='string'||typeof v.name!=='string'||vids.has(v.id))throw Error('廠商資料不正確。');vids.add(v.id);}
 return b;
}
export function mergeRecords(current,incoming){const byId=new Map(current.map(r=>[r.id,r]));let added=0,updated=0;for(const r of incoming){const old=byId.get(r.id);if(!old){added++;byId.set(r.id,r);}else if(Date.parse(r.updatedAt)>Date.parse(old.updatedAt)){updated++;byId.set(r.id,r);}}return {records:[...byId.values()],added,updated};}

export function validateCasino(c){if(!c||typeof c.id!=='string'||!c.id.startsWith('CASINO-')||typeof c.name!=='string'||!c.name.trim()||typeof c.description!=='string'||!Array.isArray(c.mediaIds)||c.mediaIds.some(x=>typeof x!=='string')||!Number.isFinite(Date.parse(c.updatedAt)))throw Error('賭場資料不完整，請填名稱並確認圖片。');for(const k of ['city','visitedOn'])if(c[k]!==undefined&&typeof c[k]!=='string')throw Error('賭場欄位格式不正確。');return c;}
